# Generated by Django 4.2.7 on 2023-11-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('token', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('code', models.CharField(max_length=25)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NseSheetStock',
            fields=[
                ('symbl', models.CharField(db_index=True, max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('symbl', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('price', models.FloatField(blank=True, max_length=20, null=True)),
                ('instrument_symbl', models.CharField(max_length=40)),
                ('day_open', models.FloatField(default=0, max_length=40)),
                ('price_bought', models.FloatField(default=0, max_length=40)),
                ('day_high', models.FloatField(default=40, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserFund',
            fields=[
                ('available_money', models.FloatField(max_length=25)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
