# Generated by Django 4.2.7 on 2023-11-11 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('algotrading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userfund',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=models.Index(fields=['symbl'], name='algotrading_symbl_2335a0_idx'),
        ),
        migrations.AddIndex(
            model_name='nsesheetstock',
            index=models.Index(fields=['symbl'], name='algotrading_symbl_e32a43_idx'),
        ),
        migrations.AddField(
            model_name='authcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accesstoken',
            index=models.Index(fields=['user', 'token', '-date'], name='algotrading_user_id_c0a745_idx'),
        ),
    ]
